name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jaspr

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: 📦 Install jaspr CLI
        run: dart pub global activate jaspr_cli
        working-directory: .

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🔧 Configure production base URL
        run: sed -i 's|^base: /$|base: /fhir_fli_documentation/|' content/_data/site.yaml

      - name: 🏗️ Build website
        run: $HOME/.pub-cache/bin/jaspr build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jaspr/build/jaspr
